// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq2Pn1NBePJOOIVdR3ytCHWa8OUwgRCuI',
    appId: '1:300005889763:web:88f6ad1fddf3014d3f57d6',
    messagingSenderId: '300005889763',
    projectId: 'sage-68406',
    authDomain: 'sage-68406.firebaseapp.com',
    storageBucket: 'sage-68406.firebasestorage.app',
    measurementId: 'G-K66QDD8VCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBurgDKxqkVDwIfk9s8gRzPm2cOlFt-uVQ',
    appId: '1:300005889763:android:8ec6641ce6d66e933f57d6',
    messagingSenderId: '300005889763',
    projectId: 'sage-68406',
    storageBucket: 'sage-68406.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmWOA8NOc9wHLqVRvvUZScoa3Uag6AL0Y',
    appId: '1:300005889763:ios:559323cef1ada8ee3f57d6',
    messagingSenderId: '300005889763',
    projectId: 'sage-68406',
    storageBucket: 'sage-68406.firebasestorage.app',
    iosClientId: '300005889763-73haj03g22s3i2gh5sr1n6mmvgevlgbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sage',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmWOA8NOc9wHLqVRvvUZScoa3Uag6AL0Y',
    appId: '1:300005889763:ios:559323cef1ada8ee3f57d6',
    messagingSenderId: '300005889763',
    projectId: 'sage-68406',
    storageBucket: 'sage-68406.firebasestorage.app',
    iosClientId: '300005889763-73haj03g22s3i2gh5sr1n6mmvgevlgbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq2Pn1NBePJOOIVdR3ytCHWa8OUwgRCuI',
    appId: '1:300005889763:web:340786d7da13f0113f57d6',
    messagingSenderId: '300005889763',
    projectId: 'sage-68406',
    authDomain: 'sage-68406.firebaseapp.com',
    storageBucket: 'sage-68406.firebasestorage.app',
    measurementId: 'G-FTFE5F3Z9J',
  );
}
